steps:
- name: 'golang:1.19.2'
  env: ['PROJECT_ROOT=hello-app']
  args: ['go', 'build', '-o', 'main', 'main.go']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west1-docker.pkg.dev/qwiklabs-gcp-03-426e90a93bc3/my-repository/hello-cloudbuild:v1.0', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west1-docker.pkg.dev/qwiklabs-gcp-03-426e90a93bc3/my-repository/hello-cloudbuild:v1.0']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'prod/deployment.yaml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=europe-west1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=hello-cluster'
